## YAML Template.
---
spring:
  datasource:
    url: jdbc:h2:mem:mydatabase
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
        